### ISSUE TITLE
lang state do not persist after page reload (and other...)

### ISSUE THREAD

**Issue by AdsonCicilioti** [elvessousa/next-intl#1]
Hi Elves,

Nice solution with this project. U help me very a lot.

Sorry for my poor knowledge but i would like know how make persist the lang state after page reload.
Another question a bit more complex, would be how create content from a cms-headless like a Strapi.

(I've comment on your article - part 2)

**Comment by elvessousa** [comment]
Hello, Adson! Thank you for the feedback, it will be fixed right away.
About the Strapi stuff, I plan to make a version of this repo to make it available for a headless CMS.
 
Sorry for the late response. I only saw your issue today.

**Comment by elvessousa** [comment]
I believe I solved the problem. It forgot setting a localStorage to persist state after refresh, so that's the culprit! 

I'll close this issue for now. Thanks a lot!
