### ISSUE TITLE
Server Error for Articels and About Page

### ISSUE THREAD

**Issue by AAAeng** [elvessousa/next-intl#8]
If I go to this two pages I receive the following error.

TypeError: Cannot read properties of undefined (reading 'replace')

in file: src\lib\files.ts (31:38) @ eval
` const id = fileName.split('/')[1].replace(/\.md$/, "");`

How can I solve this problem

**Comment by elvessousa** [comment]
Sorry for the late response. GitHub is not mailing me on new issues.
In which pages are these errors shown?

**Comment by elvessousa** [comment]
Thanks for creating this issue. This was due to a change in Remark's exports. The default export was to changed to a named one. Changing that was enough to solve, in my case. Test again and see if the error persists.
